version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - npm install -g aws-sam-cli
      - cd src                # Navigate to the src directory
      - npm install
  build:
    commands:
      - sam build
  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket $S3_BUCKET_NAME
      - aws cloudformation deploy --template-file packaged.yaml --stack-name $STACK_NAME --capabilities CAPABILITY_IAM