AWSTemplateFormatVersion: '2010-09-09'
Description: AWS SAM Deployment Template for Northstar

Resources:
  NorthstarDeployment:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://s3.amazonaws.com/${S3BucketName}/packaged.yaml"
      Parameters:
        StageName: Prod
