AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  northstar - serverless journalling app with chatgpt integration to summarize the journal entry. to test out if it works. 

Resources:
  JournalTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JournalEntries
      AttributeDefinitions:
        - AttributeName: EntryID
          AttributeType: S
      KeySchema:
        - AttributeName: EntryID
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  WriteJournalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: writeJournal.lambdaHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          TABLE_NAME: !Ref JournalTable
      Events:
        WriteJournalApi:
          Type: Api
          Properties:
            Path: /journal
            Method: post

  RetrieveJournalFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: retrieveJournal.lambdaHandler
      Runtime: nodejs20.x
      Environment:
        Variables:
          TABLE_NAME: !Ref JournalTable
      Events:
        RetrieveJournalApi:
          Type: Api
          Properties:
            Path: /journal/{id}
            Method: get

Outputs:
  WriteJournalApi:
    Description: "Endpoint for writing journal entries"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/journal"

  RetrieveJournalApi:
    Description: "Endpoint for retrieving journal entries"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/journal/{id}"
